empleados_django/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import ListAllEmpleados, ListByAreaEmpleados, ListByJobEmpleados, ListEmpleadosByKword, \
    ListHabilidadesEmpleado, EmpleadoDetailView, EmpleadoCreateView, Successview, EmpleadoUpdateView, InicioView

app_name = 'persona_app'

urlpatterns = [
    path('', InicioView.as_view(), name='inicio'),
    path(
        'listar-todo-empleados/',
        ListAllEmpleados.as_view(),
        name = "empleados_all",
    ),
    path('listar-by-area/<shorname>', ListByAreaEmpleados.as_view()),
    path('listar-by-trabajo/<job>', ListByJobEmpleados.as_view()),
    path('buscar-empleado/', ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', EmpleadoDetailView.as_view()),
    path('add-empleado/', EmpleadoCreateView.as_view()),
    path('success/', Successview.as_view(), name='correct'),
    path('update-empleado/<pk>/', EmpleadoUpdateView.as_view(), name='modificar_empleado'),

]

empleados_django/empleados_django/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
import applications

urlpatterns = [
    path('admin/', admin.site.urls),
    #inclimos las url de la app departamentos
    re_path('', include('applications.departamentos.urls')),
    #inclimos las url de la app persona
    re_path('', include('applications.persona.urls')),
    #incluimos las url de home
    re_path('', include('applications.home.urls')),
]

empleados_django/templates/includes/header.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li class="has-submenu">
        <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
      </li>
      <li><a href="#0">Departamentos</a></li>
      <li><a href="#0">Administrar</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="buscar empleados"></li>
      <li><button type="button" class="button">registrar nuevo</button></li>
    </ul>
  </div>
</div>